apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-02
data:
  release_name: {{ .Release.Name }}
  release_service: {{ .Release.Service }}
  Chart: {{ .Chart.Name}}-{{ .Chart.Version }}
  Template: {{ .Template.Name}}
  code: |-
{{ .Files.Get "files/sample.conf" | nindent 4 }}
